import "./globals.css";
import Menu from "./components/menu";
import Load from "./components/load";
export const metadata = {
  title: "Gosu Battle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Menu />
      <Load />
      {children}
    </>
  );
}
